version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/src"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    assignees:
      - "gabraganca"

  - package-ecosystem: "docker"
    directory: "/src"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    assignees:
      - "gabraganca"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "gabraganca"