version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/src"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    assignees:
      - "gabraganca"

  - package-ecosystem: "docker"
    directory: "/src/worker"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    assignees:
      - "gabraganca"

  - package-ecosystem: "docker"
    directory: "/src/api"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    assignees:
      - "gabraganca"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "gabraganca"
